### PR TITLE
Makefile: Make sure make is invoked with appropriate permissions

### PR DESCRIPTION
**Pull request by BjoernDaase**

### CODE REVIEW

**Comment by Antynea** [comment]
Good catch, thank you for your contribution !

**Comment by sgn** [comment]
Hello,
But I think this change is not that necessary:
- In case someone wants to install into system directories directly, they'll be complaint as insufficient permission anyway.
- For those distros, that would like to install into `$(DESTDIR)`, this change requires us to either add `fakeroot` to package's build-depends, or revert this one out :(

**Comment by Antynea** [comment]
Hello @sgn ,

I understand your arguments, 
do you want the commit to be cancelled ?
or
do you want to propose your own fix ?

**Comment by sgn** [comment]
I _think_ this change should be reverted, or _partial_ reverted.

While I think `make install` shouldn't care about the `UID`, I don't have any strong opinons for `make uninstall`.

**Pull request merged**
