### PR TITLE
Several edits and tweaks to the README

### PR DESCRIPTION
**Pull request by danboid**
I've attempted to improve the readability and grammar of the README. The main thing I've changed is the Timeshift instructions to cover the config for both old and new versions  in the same section.

I think there is still quite a lot that could be done to improve the README but I think this should do for the moment.

### CODE REVIEW

**Comment by danboid** [comment]
One bit I was unsure about was this:

"Once the entry for the sub menu was generated grub-btrfs puts the actual sub menu into the file grub-btrfs.cfg. So to generate snapshot entries in the sub menu it is usually enough to run only the script with sudo /etc/grub.d/41_snapshots-btrfs"

Why would the user want to update the grub-btrfs.cfg without also updating grub, unless they were developing/debugging grub-btrfs? Maybe there is a valid reason to do this so I left that bit in.

**Comment by Schievel1** [comment]
> One bit I was unsure about was this:
> 
> 
> 
> "Once the entry for the sub menu was generated grub-btrfs puts the actual sub menu into the file grub-btrfs.cfg. So to generate snapshot entries in the sub menu it is usually enough to run only the script with sudo /etc/grub.d/41_snapshots-btrfs"
> 
> 
> 
> Why would the user want to update the grub-btrfs.cfg without also updating grub, unless they were developing/debugging grub-btrfs? Maybe there is a valid reason to do this so I left that bit in.

It's a lot safer to only change the submenu because you can't end up with a system that not able to boot.

**Comment by Schievel1** [comment]
Thanks for that. Antynea and me are not native English speakers so it can happen that grammar is a little awkward from time to time. 

You want to continue on my other project? I just finished the readme today. ;-) https://github.com/Schievel1/mview

**Review by Schievel1 — APPROVED** [review]

**Comment by danboid** [comment]
@Schievel1 Yes I spotted your @ .de email so I realised English wasn't your first language but don't worry because your English is good. 

I'm a bit off a stickler for docs for any programs that I use a lot or think are important.

Once this PR gets merged I'm tempted to do a tutorial video on installing Debian to best take advatage of BTRFS snapshots. I could do one on ZFS snapshots too as I'm even more familar with them but I think the BTRFS one would be more useful because its more dual/multi boot friendly than ZFS.

**Comment by danboid** [comment]
It seems @Antynea has to approve this too before it can be pulled?

**Comment by Schievel1** [comment]
> It seems @Antynea has to approve this too before it can be pulled?

No, not really. I just wasn’t at a computer and I prefer not to merging and such with my cell phone

**Comment by danboid** [comment]
I'm the same.

**Pull request merged**
