### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by maximbaz**
@Antynea I'm packaging this to official Arch Linux repos now, and I'm creating a Makefile to make it simpler.

I also renamed localisation file, now the file name is controlled by `PKGNAME` variable passed to Makefile, e.g. `make PKGNAME=grub-btrfs-git install`.

I haven't tested localisation, but I believe it has to match the application name.

Please have a look, and if everything seems alright to you, please merge and make a new release 😉

### CODE REVIEW

**Comment by Antynea** [comment]
Hello,

I removed the localization feature in the script since version 3.0,
I didn't like his implementation,
but I didn't notify that.
I forgot to delete the "localisation" folder.

Looking at this #56 
@N-Parsons asked if `10-update_grub.conf` file was still useful
What do you think ?

**Comment by maximbaz** [comment]
I removed the localization folder and updated Makefile.

Huh, I didn't know about #56 and the existence of systemd services, that's why I didn't even have them in my Arch Linux package yet 🙂 So if I understand correctly, `10-update_grub.conf` is a way to update grub-btrfs entries after `snapper-timeline` service has run, while `grub-btrfs.service` is a generic service that you can run at any time? 

If we are to remove `10-update_grub.conf`, I suggest we bump major version (i.e. `grub-btrfs v4`), so that people are notified that they need to adjust their configs.

To clarify, what is the point of `grub-btrfs.service`, why not just run `grub-mkconfig -o /boot/grub/grub.cfg`? Only to allow configurable path to `grub-mkconfig`?

**Comment by Antynea** [comment]
> So if I understand correctly, 10-update_grub.conf is a way to update grub-btrfs entries after snapper-timeline service has run, while grub-btrfs.service is a generic service that you can run at any time?

Exactly.

> If we are to remove 10-update_grub.conf, I suggest we bump major version (i.e. grub-btrfs v4), so that people are notified that they need to adjust their configs.

Yes, I have to make corrections before push a new version, such as:

* Deleted `localisation `folder
* Deleted `10-update_grub.conf`
* Remove the "executable" attribute on both `grub-btrfs.path/service` files
* Update the readme to explain how to use the new services. 
(copy grub-btrfs.path and grub-btrfs.service to `/etc/systemd/system/` and enable/start `grub-btrfs.path` to services works.)

> To clarify, what is the point of grub-btrfs.service ...

`10-update_grub.conf`, only works with `snapper`
`grub-btrfs.path` + `grub-btrfs.service`
works without `snapper`.

With `grub-btrfs.path`, whenever a change (add or delete) occurs in the `/.snapshot` folder,
`grub-btrfs.service` will be executed to update "grub"

For people like me who don't use `snapper `it's perfect.
In addition the command `grub-mkconfig` and the destination folder for `grub` is configurable via "41_snapshots-btrfs_config" which was requested for people using this script on other distribution such as "fedora, etc ..." where the command `grub-mkconfig` become `grub2-mkconfig` as well as the folder `/boot/grub` become `/boot/grub2`.

Have I answered your questions?

Ps: `/.snapshot ` is hard code in `grub-btrfs.path`, so this requires that the subvolume containing "snapshots" be mounted there.

**Comment by maximbaz** [comment]
Thanks @Antynea, makes perfect sense! 

I reverted some changes to keep this PR only about Makefile, I believe now it follows the intended installation bundle for `4.0.0`.

Have a look if it's ok now. If you want, I can make another PR for those corrections you mention (except README), but I guess they are faster for you to make on your own while documenting new approach 🙂

**Comment by Antynea** [comment]
I realize that now, but
`@install -Dm755 -t "$(DESTDIR)/etc/grub.d" 41_snapshots-btrfs_config`
This should be : 644
We don't want the `grub-mkconfig` command to execute this file.

Otherwise everything is good.
Waiting correction before merge

**Comment by maximbaz** [comment]
Nice suggestions. Check the latest one out, do you like file just being named `config`? It's simple and still clear because it will be installed in `/etc/default/grub-btrfs`. If not, I can revert the rename.

**Comment by Antynea** [comment]
@maximbaz 
I have no preference.
What is the use in this case?

**Comment by maximbaz** [comment]
Use is exactly the same, `config` file is placed in `/etc/default/grub-btrfs/config` as you suggested, and now `41_snapshots-btrfs` is reading that file before doing its work. Unless I misunderstood the question?

**Comment by Antynea** [comment]
@maximbaz 
Oh sorry, I misspoke.
What is the procedure to follow.
Create a `grub-btrfs folder` and a `config file`
**or**
create `grub-btrfs-config file` without folder
in /etc/default/

I have no preference, but i find no information that explains the correct procedure.
Oh, and remove any reference to `/etc/default/grub`.

In V4.0, we no longer reference this file `/etc/default/grub`

**Comment by maximbaz** [comment]
Gotcha 👍 The procedure is to create `/etc/default/grub-btrfs` folder and put inside it a `config` file from this repo.

Lets have Makefile be the source of truth on what is the recommended installation procedure, this line tells people to copy `config` folder in `/etc/default/grub-btrfs/` folder.

```
@install -Dm644 -t "$(DESTDIR)/etc/default/grub-btrfs/" config
```

**Comment by Antynea** [comment]
We are ok
merge it :)

**Comment by maximbaz** [comment]
Just pushed more cleanup. Merging! :)

**Comment by maximbaz** [comment]
Let me know if you need more help on 4.0 release, I've just seen you are already preparing a branch 👍

**Comment by Antynea** [comment]
I work on it,
when I'm done, I'll pull-request,
and it will ask for proofreading, my english is poor ^^

**Pull request merged**
