### PR TITLE
Boot on read-only snapshot

### PR DESCRIPTION
**Pull request by Antynea**
## Boot on read-only snapshot
Fix: #92 

* Create a initramfs folder & configuration files
  * Create a initramfs folder.
  * Create Arch Linux folder.
  * Add config files to generate a custom initrafms for boot on read-only snapshot for Arch Linux.
  * Adds a readme file to explain how it works and how to install it.

* Update Readme
  * Updates the documentation to be able to boot on a read-only snapshot.
  * Redesign readme again.

### CODE REVIEW

**Comment by Antynea** [comment]
Hi,
Do I need to update the `Makefile` file to add this feature ?

**Comment by maximbaz** [comment]
This is really cool stuff @Antynea, I'm looking forward to try it out as well some time later!

To answer your question, yes, modifying `Makefile` would be very appreciated. As far as I understood from this PR, you basically want two more files to be installed in `/etc/initcpio/{install,hooks}` folders. These are correct folders when users are doing stuff by hand, but in `Makefile` you should use `/usr/lib/initcpio/{install,hooks}/` folder instead, it's just convention I think.

So, I would expect the lines you need to add to `Makefile` are (writing by hand on Github, so not tested, but should be right):

```Makefile
install:
    ...
    @install -Dm644 "initrafms/Arch Linux/overlay_snap_ro-install" "$(LIB_DIR)/initcpio/install/overlaysnapro"
    @install -Dm644 "initrafms/Arch Linux/overlay_snap_ro-hook" "$(LIB_DIR)/initcpio/hooks/overlaysnapro"
```

(and removal of these files in `uninstall:` too).

By the way, maybe consider naming the hook `grub-btrfs-recovery` instead of `overlaysnapro`, just to make it easier to indicate the origin of the hook? Not important though, just an idea.

Otherwise, looks very very nice 👍 

If you want, when you are ready with this PR, we can give somebody from #92 an Arch package for test run, to be certain that the procedure works as expected before you make a release (so, ping me and I will compile Arch package and attach it in that thread) - but if it is too long to wait, we can of course just make a release 😉

**Comment by maximbaz** [comment]
> If I include the installation of these 2 files in the makefile, it means that they will be installed with the grub-btrfs package. How can I inform the user about its use ?

I recommend a combination of these actions:

1. Add docs to the package, i.e. in `Makefile` add two more lines:

```Makefile
install:
    ...
    @install -Dm644 -t "$(SHARE_DIR)/doc/$(PKGNAME)/" README.md
    @install -Dm644 "initramfs/readme.md" "$(SHARE_DIR)/doc/$(PKGNAME)/initramfs-recovery.md"
```

Some people will notice new doc and will read it. 

2. Increase major version (i.e. next release to become `5.0`), some people pay extra attention when major version changes - but on the other hand may be overkill...

3. Write something in Github release, preferably with a link to `initramfs/readme.md`, say that now it's possible to recover, and here is link for more info.

4. We will post in #92, it seemed quite a number of users are following that thread.

What do you think, sounds good?

**Comment by Antynea** [comment]
Thank you for your suggestions,
i'm going to act.

1- I'm ok
2- The next release [5.0](https://github.com/Antynea/grub-btrfs/releases/tag/untagged-0961855df25e74247d96) is not ready.
It lacks the most important feature requested for years.
Namely, add the possibility to integrate snapshots present on another device/partition.
For example snapshots on a backup device.
All the commits made since the last release, are there to prepare this feature. (This PR is part of it)
3- Already done in this PR c740242, i think
4- I'm ok

**Comment by Antynea** [comment]
@maximbaz 
Finally I decided to release version 4.7.

**Comment by maximbaz** [comment]
It's updated 👍

**Comment by Antynea** [comment]
Love you 👍

**Comment by Antynea** [comment]
it's strange:
```
Package Contents
etc/
etc/default/
etc/default/grub-btrfs/
etc/default/grub-btrfs/config
etc/grub.d/
etc/grub.d/41_snapshots-btrfs
usr/
usr/lib/
usr/lib/initcpio/
usr/lib/initcpio/install/
usr/lib/initcpio/install/grub-btrfs-overlayfs
usr/lib/systemd/
usr/lib/systemd/system/
usr/lib/systemd/system/grub-btrfs.path
usr/lib/systemd/system/grub-btrfs.service
usr/share/
usr/share/doc/
usr/share/doc/grub-btrfs/
usr/share/doc/grub-btrfs/README.md
usr/share/doc/grub-btrfs/initramfs-overlayfs.md
usr/share/licenses/
usr/share/licenses/grub-btrfs/
usr/share/licenses/grub-btrfs/LICENSE
```

OMG, shame on me...
In [Makefile ](https://github.com/Antynea/grub-btrfs/blob/0ed5adaf3255133edf2d15e910420e2cdcc7dcab/Makefile#L16): 
I made a mistake somewhere.
This line is a duplicate ...
Should be:
```
@install -Dm644 "initramfs/Arch Linux/overlay_snap_ro-hook" "$(LIB_DIR)/initcpio/hooks/grub-btrfs-overlayfs"	# Arch Linux only
```

Sorry for wasting your time, I need to correct this.

**Comment by Antynea** [comment]
@maximbaz 
[v4.7.1](https://github.com/Antynea/grub-btrfs/releases/tag/v4.7.1)
Corrects this mistake, sorry ... 
Can you update again ?

**Comment by maximbaz** [comment]
No problem, updated 😉

**Pull request merged**
