### PR TITLE
Modular Configuration

### PR DESCRIPTION
**Pull request by teldra**

### CODE REVIEW

**Comment by Antynea** [comment]
Hello @teldra ,

Can you tell me why you need these changes ?

**Comment by teldra** [comment]
I am installing a small fleet of laptops and I thought, dropping in files with different configs would be awesome to automate this.

**Comment by Antynea** [comment]
The idea is interesting.
However, your solution is incomplete.

If you have check the box "Allow edits from maintainers" i can do it for you.

**Comment by teldra** [comment]
I checked the box. :)

**Comment by Antynea** [comment]
Hello @teldra ,

After several unsuccessful attempts, it isn't possible to make the configuration modular.

Indeed, the ```grub-btrfs.service``` requires a single configuration file to be executed properly.

Because of the `systemd `variable architecture, in particular:
```EnvironmentFile``` which requires a separate file per declaration, it isn't possible to assign multiple configuration files per declaration to it.

Also, to satisfy your request, I wouldn't have used ```/etc/conf.d``` folder but a different one, like ```/etc/grub-btrfs/conf.d```
```/etc/conf.d``` inherited from ```init System V```, now replaced by ```systemd``` on most distributions.
It is therefore not appropriate to use it.

if a workaround to use `grub-btrfs.service` is possible, I would be glad to apply it, in order to continue the work on your request.

Therefore, I ask you again:
Can you tell me why you need these changes?

If you use ``make install`` command, indeed, this can be a problem.
because your said
> I am installing a small fleet of laptops and I thought, dropping in files with different configs would be awesome to automate this.

However, I encourage you to create a package for your distribution so that you don't suffer from the weaknesses imposed by the ```make install``` command.

`Homebrew` `Pacman ` `dpkg ` `RPM ` etc... uses mechanisms to prevent overwriting the `/etc/default/grub-btrfs/config` file.
Perhaps this is your solution.
 
If I am wrong, and don't answer your request correctly, please let me know.

Note: Don't forget, I would be happy to continue working on your request, if a workaround is found for `grub-btrfs.service`.

**Comment by teldra** [comment]
First: Thank you for your effort!
Since I am using a distribution with runit, I overlooked everything systemd specific and I understand, why there is a need for a single file.

>  Can you tell me why you need these changes?

It's not that I need it, but I thought it was a good idea and easy possible, since I am not restricted by systemd.

So, I will close this PR, because I don't have a single clue, how to `systemd` this idea.

**Pull request closed without merging**
